import { useEffect, useState } from 'react';
import { get, push, ref, remove, update } from 'firebase/database';
import { database } from '../firebase';

const empty={title:'',description:'',status:'new',dueDate:''};
export default function Tasks(){
 const [items,setItems]=useState({}),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true);
 async function load(){try{const s=await get(ref(database,'requests'));setItems(s.exists()?s.val():{})}catch(e){alert('Грешка при зареждане: '+e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const save=async e=>{e.preventDefault();if(!form.title.trim())return alert('Въведи задача.');try{const data={...form,title:form.title.trim(),updatedAt:Date.now()};if(editing){await update(ref(database,'requests/'+editing),data);setItems(p=>({...p,[editing]:{...p[editing],...data}}))}else{const r=push(ref(database,'requests'));const x={...data,createdAt:Date.now()};await update(r,x);setItems(p=>({...p,[r.key]:x}))}setForm(empty);setEditing(null)}catch(e){alert('Грешка при записване: '+e.message)}};
 const del=async id=>{if(!confirm('Изтрий задачата?'))return;await remove(ref(database,'requests/'+id));setItems(p=>{const n={...p};delete n[id];return n})};
 const list=Object.entries(items).map(([id,x])=>({id,...x}));
 return <section className="page-card"><div className="page-heading"><div><h1>Списък Задачи</h1><div className="breadcrumb">Начало / Списък Задачи / Листване</div></div><button className="btn btn-primary" onClick={()=>{setEditing(null);setForm(empty)}}>+ Добави</button></div>
 <div className="module-form"><h2>{editing?'Редактиране на задача':'Нова задача'}</h2><form onSubmit={save} className="form-grid"><label>Задача<input name="title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Срок<input type="date" name="dueDate" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Статус<select name="status" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="new">Нова</option><option value="in-progress">В процес</option><option value="done">Приключена</option></select></label><label>Описание<textarea name="description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="form-actions"><button className="btn btn-primary">Запази</button>{editing&&<button type="button" className="btn btn-light" onClick={()=>{setEditing(null);setForm(empty)}}>Отказ</button>}</div></form></div>
 <div className="table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>Задача</th><th>Описание</th><th>Срок</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{loading?<tr><td colSpan="6" className="empty-row">Зареждане...</td></tr>:list.length?list.map(x=><tr key={x.id}><td>{x.id}</td><td><strong>{x.title||x.description||'—'}</strong></td><td>{x.description||'—'}</td><td>{x.dueDate||x.date||'—'}</td><td><span className="status-badge">{x.status||'new'}</span></td><td><button className="table-action edit-action" onClick={()=>{setEditing(x.id);setForm({...empty,...x})}}>Редактирай</button> <button className="table-action danger" onClick={()=>del(x.id)}>Изтрий</button></td></tr>):<tr><td colSpan="6" className="empty-row">Няма задачи.</td></tr>}</tbody></table></div><div className="pagination"><span>Брой записи: {list.length}</span></div></section>;
}
